dist: trusty
language: node_js
cache: yarn
node_js:
- '10'
install:
- yarn install --frozen-lockfile
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint
- yarn test
